try {
  var 1 = 1;
} catch (IOException ex) {
}
// this new another
try {
  var 1 = 1;
} catch (IOException ex) {
}