try {
  var 1 = 1;
} catch (Exception ex) {
  print(1)
}